#!/usr/bin/env bash

COVER_PATH="$HOME/.tmp"
status=$(mpc status)

ARTIST=$(mpc current -f %artist%)
ALBUM="󰀥  $(mpc current -f %album%)"
TITLE="󰝚  $(mpc current -f %title%)"

is_stopped=$(mpc status | awk '{ print $2 }')
is_repeat=$(mpc status | rg 'repeat' | awk '{ print $4 }')
is_random=$(mpc status | rg 'random' | awk '{ print $6 }')
is_playing=$(mpc status | rg '\[' | awk '{ print $1 }' | tr -d '\[\]]')

if [ -z "$status" ]; then
	prompt="Offline"
	message="MPD is Offline"
elif [ "$is_stopped" = "n/a" ]; then
	prompt="Stopped"
	message="Playback stopped"
else
    if [ -e "$COVER_PATH/raw_cover.png" ]; then
        cover="$COVER_PATH/raw_cover.png"
    else
        mpc readpicture "$(mpc current -f %file%)" > "$COVER_PATH/raw_cover.png" 2> /dev/null
        cover="$COVER_PATH/raw_cover.png"
    fi

	prompt="$ARTIST"
    message="""$TITLE
$ALBUM"""
fi

toggle_play_pause() {
    if [ -n "$status" ]; then
        mpc -q toggle
        dunstify "$(mpc status | rg '\[' | awk '{ print $1 }' | tr -d '\[\]]' | sed 's/p/P/' )"
    fi
}
stop_palyback() {
    mpc -q stop
    dunstify "Playback stopped"
}
toggle_random() {
    if [ -n "$status" ]; then
        mpc -q random
        dunstify "Random: $(mpc status | rg 'random' | awk '{ print $6 }')"
    fi
}
toggle_repeat() {
    if [ -n "$status" ]; then
        mpc -q repeat
        dunstify "Repeat: $(mpc status | rg 'repeat' | awk '{ print $4 }')"
    fi
}
next_track() {
    if [ "$is_stopped" != "n/a" ] && [ -n "$status" ]; then
        mpc -q next
        songchanged
    fi
}
prev_track() {
    if [ "$is_stopped" != "n/a" ] && [ -n "$status" ]; then
        mpc -q prev
        songchanged
    fi
}

if [ "$is_playing" = "playing" ]; then
    toggle_opt="󰏤"
else
    toggle_opt="󰐊"
fi
prev_opt="󰒮"
next_opt="󰒭"
stop_opt="󰓛"
random_opt="󰒝"
repeat_opt="󰑖"

if [ "$is_repeat" = "on" ] && [ "$is_random" = "on" ]; then
    active="4,5"
elif [ "$is_repeat" = "on" ]; then
    active="4"
elif [ "$is_random" = "on" ]; then
    active="5"
else
    active=""
fi
urgent=""
if [ "$is_stopped" = "n/a" ]; then
    urgent="3"
fi

opt_menu() {
    rofi -dmenu \
		-theme-str "inputbar {background-image: url(\""$cover"\", width);}" \
        -p "$prompt" \
        -mesg "$message" \
        -a "${active}" -u "$urgent" \
        -theme $XDG_CONFIG_HOME/rofi/themes/musicdash.rasi
}

run_rofi(){
    echo "$prev_opt\n$toggle_opt\n$next_opt\n$stop_opt\n$repeat_opt\n$random_opt" | opt_menu
}
state=$(run_rofi)

case "$state" in
    "$toggle_opt") toggle_play_pause
    ;;
    "$stop_opt") stop_palyback
    ;;
    "$next_opt") next_track
    ;;
    "$prev_opt") prev_track
    ;;
    "$repeat_opt") toggle_repeat
    ;;
    "$random_opt") toggle_random
    ;;
    *) echo "Don't know what to do"
    ;;
esac
