#!/data/data/com.termux/files/usr/bin/sh
#!/usr/bin/env bash

killall -q picom dunst

xrdb $HOME/.Xresources
picom &
dunst &
feh --no-fehbg --bg-fill $XDG_CONFIG_HOME/bg/tanya1.jpeg &
$XDG_CONFIG_HOME/polybar/launch.sh
