#!/usr/bin/env sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
$XDG_CONFIG_HOME/bspwm/autostart

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color  "#6e6a86"
