#!/usr/bin/env bash

killall -9 -q picom dunst bspc sxhkd

xrdb -merge $HOME/.Xresources
picom -b

feh -z --no-fehbg --bg-fill $XDG_CONFIG_HOME/bg

dunst &
sxhkd &

sh $XDG_CONFIG_HOME/polybar/scripts/launch.sh
