#!/usr/bin/env bash

killall -q picom dunst
pkill sxhkd

xrdb -merge $HOME/.Xresources
picom -b

feh -z --no-fehbg --bg-fill $XDG_CONFIG_HOME/bg

dunst &
sxhkd &

sh $XDG_CONFIG_HOME/polybar/launch.sh
