#!/usr/bin/env sh

bspc rule -r *
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 6 7 8

bspc config border_width 2
bspc config window_gap 8
bspc config split_ratio 0.51
bspc config top_padding 0
bspc config bottom_padding 0

bspc config automatic_scheme alternate
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config presel_feedback_color "#191724"
bspc config focused_border_color "#9ccfd8"
bspc config normal_border_color "#6e6a86"

xrdb -merge $XDG_CONFIG_HOME/X11/xresources
xsetroot -cursor_name left_ptr
setxkbmap us dvorak -option ctrl:nocaps
xcape -e '#66=Escape'
brillo -I &

$XDG_CONFIG_HOME/polybar/scripts/launch.sh
autostart="mpd dunst sxhkd picom bspwm-swallow bspwm-fullscreen"
for program in $autostart; do
	pgrep -fx $program >/dev/null || $program &
done &

feh -z --no-fehbg --bg-fill ~/Pictures/Walls &
betterlockscreen -u ~/Pictures/Walls &

bspc rule -a st-256color desktop='^1' follow=on focus=on
bspc rule -a Firefox desktop='^2' state=fullscreen follow=on focus=on
bspc rule -a mpv desktop='^3' state=fullscreen follow=on focus=on
bspc rule -a Ncmpcpp desktop='^3' state=floating follow=on focus=on rectangle=860x610+12+42
bspc rule -a Zathura desktop='^4' follow=on focus=on
bspc rule -a Virt-viewer desktop='^5' state=floating follow=on focus=on
bspc rule -a transmission desktop='^5' state=floating follow=on focus=on rectangle=620x374+1286+51
bspc rule -a CustomFloat focus=on sticky=on state=floating rectangle=620x390+960+42
