#!/usr/bin/env sh

bspc rule -r *
bspc monitor -d 1 2 3 4 5

bspc config border_width			2
bspc config window_gap				8
bspc config split_ratio				0.51
bspc config top_padding				0
bspc config bottom_padding			0
bspc config automatic_scheme		alternate
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config presel_feedback_color	"#191724"
bspc config focused_border_color	"#9ccfd8"
bspc config normal_border_color		"#6e6a86"

$XDG_CONFIG_HOME/bspwm/scripts/autostart

bspc rule -a st-256color desktop='^1' follow=on focus=on
bspc rule -a Firefox desktop='^2' state=fullscreen follow=on focus=on
bspc rule -a mpv desktop='^3' state=fullscreen follow=on focus=on
bspc rule -a Ncmpcpp desktop='^3' state=floating follow=on focus=on rectangle=860x610+12+42
bspc rule -a Zathura desktop='^4' follow=on focus=on
bspc rule -a transmission desktop='^5' state=floating follow=on focus=on rectangle=620x374+1286+51
bspc rule -a CustomFloat focus=on sticky=on state=floating rectangle=620x390+960+42
