#!/usr/bin/env sh

INTERNAL_MONITOR="eDP1"
EXTERNAL_MONITOR="HDMI1"

bspc rule -r *

if [ -n "$(xrandr -q | rg -w "${EXTERNAL_MONITOR} connected")" ]; then
	bspc monitor "$EXTERNAL_MONITOR" -d 1 2 3 4 5
	bspc monitor "$INTERNAL_MONITOR" -d 6 7 8 9 10
	bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
else
	bspc monitor "$INTERNAL_MONITOR" -d 1 2 3 4 5 6
fi
# bspc monitor -d 1 2 3 4 5 6

bspc config border_width 2
bspc config window_gap 4
bspc config split_ratio 0.51
bspc config top_padding 0
bspc config bottom_padding 0

bspc config automatic_scheme alternate
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

bspc config presel_feedback_color "#191724"
bspc config focused_border_color "#ebbcba"
bspc config normal_border_color "#6e6a86"

brillo -I &
pkill redshift

autostart="picom mpd battery sxhkd bspwm-swallow bspwm-fullscreen"
for program in $autostart; do
	pkill -f $program
	$program &
done &
sh $XDG_CONFIG_HOME/polybar/scripts/launch.sh &

feh -z --no-fehbg --bg-fill ~/Pictures/Walls/flower.jpg &

bspc rule -a st-256color desktop='^1' follow=on focus=on
bspc rule -a Firefox desktop='^2' follow=on focus=on
bspc rule -a mpv desktop='^3' state=fullscreen follow=on focus=on
bspc rule -a Ncmpcpp desktop='^3' state=floating follow=on focus=on rectangle=860x610+12+42
bspc rule -a Zathura desktop='^4' state=fullscreen follow=on focus=on
bspc rule -a transmission desktop='^6' state=floating follow=on focus=on
bspc rule -a CustomFloat focus=on sticky=on state=floating rectangle=620x390+960+42
bspc rule -a Lutris desktop='^5' follow=on focus=on

floating="obsidian discord steam Upwork Virt-viewer TelegramDesktop Slack Thunderbird burp-StartBurp"
for app in $floating; do
	bspc rule -a $app desktop='^6' state=floating follow=on focus=on
done
