#!/usr/bin/env sh

xrdb -merge $XDG_CONFIG_HOME/X11/xresources
xsetroot -cursor_name left_ptr
setxkbmap -option ctrl:nocaps
brillo -I &

$XDG_CONFIG_HOME/polybar/scripts/launch.sh
autostart="mpd dunst sxhkd picom bspwm-swallow bspwm-fullscreen"
for program in $autostart; do
	pgrep -fx $program >/dev/null || $program &
done &
feh -z --no-fehbg --bg-fill ~/Pictures/Walls &
betterlockscreen -u ~/Pictures/Walls &
