#!/usr/bin/env sh

pr="$(awk "/\<color11\>/ {print \$2}" ~/.config/X11/xresources)"
is_muted=$(amixer -c 0 get Speaker | awk '/Left:/ {print $7}' | tr -d "\n\[\]")
volume=$(amixer -c 0 get Speaker | awk '/Left:/ {print $5}' | tr -d "\n\[\]%")
if [ $(echo "$is_muted") = "off" ]; then
	echo "%{F#6e6a86}󰖁 muted%{F-}"
elif [ $(echo "$volume") -gt 75 ]; then
	echo "%{F$pr}%{F-} $volume%"
elif [ $(echo "$volume") -gt 35 ]; then
	echo "%{F$pr}󰕾%{F-} $volume%"
elif [ $(echo "$volume") -eq 0 ]; then
	echo "%{F$pr}%{F-} $volume%"
else
	echo "%{F$pr}%{F-} $volume%"
fi
