#!/usr/bin/env sh

xrdb $HOME/.Xresources
$XDG_CONFIG_HOME/polybar/scripts/launch.sh
autostart="mpd dunst sxhkd picom"
for program in $autostart; do
	pgrep -x $program >/dev/null || $program &
done &

feh -z --no-fehbg --bg-fill ~/Pictures/Walls
