#!/usr/bin/env sh

file_path="/media/void/Music"
filename=$(mpc current -f %file% | sed 's/\ /\\\ /g')
album_width=80

# Get the album art
ffmpeg -i "$file_path/""$filename" "~/.tmp/raw_album.png" -y 2> /dev/null &&\
  convert -resize 80x80 "~/.tmp/raw_album.png" "/tmp/album.png"

dunstify -i ~/.tmp/album.png " Now Playing"\
    "󰝚 $(mpc current -f %artist%) - $(mpc current -f %title%)"\
    "󰀥 $(mpc curren -f %album%)"
