#!/usr/bin/env sh

device=$(pactl list sinks | awk '/Name/ { print $2 }')
is_muted=$(pactl get-sink-mute "$device" | awk '{ print $2 }')
volume=$(pactl get-sink-volume "$device" | awk '{ print $5 }')
if [ $(echo "$is_muted") = "yes" ]; then
	echo "󰖁 muted" 
elif [ $(echo "$volume" | tr -d "%") -gt 75 ]; then
	echo " $volume"
elif [ $(echo "$volume" | tr -d "%") -gt 35 ]; then
	echo " $volume"
else
	echo " $volume"
fi
